/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: matousekfoto (https://sketchfab.com/matousekfoto)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/castle-of-loarre-2876fc98a198429ca34ea7f0a2dae014
title: Castle of Loarre
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/castle.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.meshNode_Material_u1_v1_0.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_1.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_2.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_3.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_4.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_5.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_6.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_7.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_8.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_9.geometry} material={materials.Material_u1_v1} />
            <mesh geometry={nodes.meshNode_Material_u1_v1_0_10.geometry} material={materials.Material_u1_v1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/castle.gltf')
