/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { A11y, useA11y } from '@react-three/a11y'
import { Html } from '@react-three/drei'


let gltf;
export default function ChildMesh(props) {
    let mesh = props.mesh
    const [clicked, setClicked] = useState(false)
    const childMeshRef = useRef()
    // Using this allows the focussed and hover state to be rendered visible
    const a11y = useA11y()
    return (
        <A11y
            key={props.index}
            role="togglebutton"
            startPressed={false}
            activationMsg={mesh.A11yMessage}
            deactivationMsg=""
            tabindex="-1"
        >
            <mesh
                key={`childMesh` + props.index}
                geometry={props.geometry}
                material={props.material}
                ref={childMeshRef}
                onClick={(e) => { setClicked(!clicked)}}
            >
                {/* should have || a11y.pressed but it isn't working */}
                {clicked && (
                    <Html distanceFactor={mesh.labelDistance}>
                        <div
                            className="content"
                            tabIndex="-1"
                        >
                            {mesh.labelContent}
                        </div>
                    </Html>
                )}
            </mesh>
         </A11y>
    )
}
