/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { A11y, useA11y } from '@react-three/a11y'
import { Html, } from '@react-three/drei'

export default function ChildMesh(props) {
    const [clicked, setClicked] = useState(false)
    const childMeshRef = useRef()
    const a11y = useA11y()

    let mesh = props.mesh

    console.log(a11y, mesh.labelContent, mesh.A11yMessage)
    return (
        // <A11y
        //     key={props.index}
        //     role="togglebutton"
        //     startPressed={false}
        //     // activationMsg={mesh.A11yMessage}
        //     deactivationMsg=""
        //     tabindex="-1"
        // >
            <mesh
                onClick={(e) => {
                    e.stopPropagation();
                    setClicked(!clicked)
                }}
                key={`childMesh` + props.index}
                geometry={props.geometry}
                material={props.material}
                ref={childMeshRef}
            >
                {clicked || a11y.focus || a11y.hover || a11y.pressed ? <meshStandardMaterial
                    attach="material"
                    color={clicked || a11y.pressed ? "purple" : a11y.focus ? "blue" : a11y.hover ? "grey" : "green"}
                /> : ""}

                {clicked && (

                    <Html distanceFactor={mesh.labelDistance}>
                        <div
                            className="content"
                            tabIndex="-1"
                        >
                            {mesh.labelContent}
                        </div>
                    </Html>
                )}
                {/* duplicate code for tab and enter clicking and mouse clicking - could be reduced but I can't get them to work in one  */}
                {a11y.pressed && (

                    <Html distanceFactor={mesh.labelDistance}>
                        <div
                            className="content"
                            tabIndex="-1"
                        >
                            {mesh.labelContent}
                        </div>
                    </Html>
                )}
            </mesh>
        // </A11y>
    )
}
