/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alena Shek (https://sketchfab.com/ShekAlena)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/trailer-040ad3bbf0c54098b90a87ac517d3901
title: Trailer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Trailer(props) {
  const { nodes, materials } = useGLTF('./assets/gltf/trailer.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['0208trailer_default']} />
      </group>
    </group>
  )
}

useGLTF.preload('./assets/gltf/trailer.gltf')
